version: "3"
services:
    app:
        stdin_open: true
        tty: true
        build: .
        ports:
            - 88:80
        restart: always
        volumes:
            - ./:/var/www/project
            - ./docker/logs/nginx/:/var/log/nginx